version: '3.8'

services:
  web:
    build: .
    container_name: fastapi-celery
    ports:
      - "8000:8000"
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
    depends_on:
      - rabbitmq
    # environment:
    #   - C_FORCE_ROOT=True  # Needed for Celery running as root
    #   - PYTHONPATH=/app    # Ensure Python can find the `app` module

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ Management Plugin
      - "5672:5672"    # RabbitMQ default port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672/api/overview"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

  celery:
    build: .
    container_name: celery
    command: celery -A tasks.celery_app worker --loglevel=info
    depends_on:
      - rabbitmq
    environment:
      - PYTHONPATH=/app
